name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Brief description of the issue
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version
      description: Run `container-use version` and paste the output
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Contents of `/tmp/container-use.debug.stderr.log` (or `$CONTAINER_USE_STDERR_FILE` if set)
      render: text
    validations:
      required: false
