name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: call
          args: build -o cu

      - name: Verify binary
        run: |
          if [ ! -f cu ]; then
            echo "Binary 'cu' was not created"
            exit 1
          fi
          echo "Binary created successfully"
          ls -la cu